### ISSUE TITLE
[知乎美化] 调整宽度到1800px, 适配1080P屏幕

### ISSUE THREAD

**Issue by SLKun** [XIU2/UserScript#11]
基本把能看到的页面都改了改, 改宽会变得奇怪的页面就没改了
因为是个体力活, 所以发一下希望后人能够省事
作者也可以考虑基于这个加一个自定义显示宽度的功能

侧栏的宽度保证原宽度(296px)不变只拉宽主内容, 顺便把私信的模态框也变大了

```css
/*AppHeader*/
.AppHeader-inner,.TopstoryPageHeader,.ColumnPageHeader-content,.ColumnPageHeader-content,.ShelfTopNav-content-s2Ys3 {
  width: 1780px !important;
  max-width: 1780px !important;
}
/*SubHeader*/
.QuestionHeader-content,.QuestionHeader-footer-inner,.SearchTabs-inner,.ProfileHeader,.ClubHeaderInfo {
  width: 1800px !important;
}
/*Two Column*/
/*Content Container*/
.Topstory-container,.Question-main,.Search-container,.QuestionWaiting,.Profile-main,.QuestionLater,.DraftList,.Collections-container,.CollectionsDetailPage,.Balance-Layout,.Notifications-Layout,.ContentLayout,.PubIndex-book,.Club-container {
  width: 1800px !important;
}
/*Main Content (Side: 306px)*/
.Topstory-mainColumn,.Question-mainColumn,.SearchMain,.QuestionWaiting-mainColumn,.Profile-mainColumn,.QuestionLater-mainColumn,.DraftList-mainColumn,.Collections-mainColumn,.CollectionsDetailPage-mainColumn,.Balance-Main,.Notifications-Main,.ContentLayout-mainColumn,.PubIndex-book-main,.Club-mainColumn {
  width: 1494px !important;
}
/*One Column*/
.Community-ContentLayout-mainColumn,.ColumnDrafts-drafts,.Chat,.Modal--fullPage,.SettingsMain,.ClubHeaderInfo-container,.LiveDetailsPage-root-cX47U,.LiveFooter-wrapper-c3WFg,.App-root-LPTY,.App-root-xejbw,.App-root-fNRdG,.App-root-63J6a,.css-ssvpr2,.css-1xy3kyp,.css-1voxft1,.css-8txec3 {
  width: 1494px !important;
  max-width: 1494px !important;
}
/*Article*/
.TitleImage,.Post-NormalMain .Post-Header,.Post-NormalMain>div,.Post-NormalSub>div {
  width: 1494px !important;
}
.Post-SideActions {
  left: calc(50vw - 897px) !important;
}
/*Creator Center*/
.Creator{
  max-width: 1800px !important;
}
.Creator-mainColumn {
  flex: 1 1 1590px !important;
}
.css-7hb6gj {
  flex: 1 1 1284px !important;
}
/*Private Message*/
.ChatBox {
  min-height: 900px !important;
}
.ChatBoxModal {
  width: 900px !important;
}
/*Salt Content*/
.Directory-pc-oGvJ9 .Directory-directory-wnMb2 {
  left: calc(50% - 747px);
}
```
