### ISSUE TITLE
[护眼模式] 刷新网页会先闪一下原来的主题颜色后脚本才会生效

### ISSUE THREAD

**Issue by langoyb** [XIU2/UserScript#399]
### 问题描述

暗色模式下，比方说油管，谷歌等网站刚打开或者是刷新网页会先短暂闪一下原主题森（也就是亮色），然后再变黑。这种闪烁有点伤眼，不知道有没有办法解决。该问题在Safari和edge均存在。
该脚本算是我用过的不管是扩展还是脚本中算最理想的一个了，感谢作者的付出。

**Comment by XIU2** [comment]
因为油猴脚本的局限性，该问题没什么好的解决方法，因为油猴脚本必须要等网页加载后才能运行，无法第一时间修改网页样式。
建议用 Stylus 扩展来插入自定义的网页样式，如模式 3：

```
html {filter: invert(0.9) !important; text-shadow: 0 0 0 !important;}
```

**Comment by langoyb** [comment]
多谢指点，有日子没玩css了，正好重新复习一下

**Comment by hqhbaby** [comment]
请教 大神 如何将护眼模式3 移值到 Stylus加载的CSS里面呢

**Comment by XIU2** [comment]
@hqhbaby 我上面不都写了吗？

**Comment by hqhbaby** [comment]
感谢大神css代码  经测试 发现有不一样   图片反而变成发色  应该如何修改呢  能否像脚本那样 排除一些 指定网站呢

**Comment by XIU2** [comment]
@hqhbaby 前面的忘记写了，还要额外给一些元素加一个反转反色的样式：

```css
img, .img, video, [style*="background"][style*="url"], svg {filter: invert(1) !important;}
```
