### ISSUE TITLE
[Github 增强 - 高速下载] 希望添加冻结顶部窗格，一键返回顶部功能

### ISSUE THREAD

**Issue by Yxuan18** [XIU2/UserScript#444]
### 功能需求

![脚本地址](https://greasyfork.org/zh-CN/scripts/412245-github-%E5%A2%9E%E5%BC%BA-%E9%AB%98%E9%80%9F%E4%B8%8B%E8%BD%BD/feedback#post-discussion)

在GitHub 的搜索页面，我们通常在搜索关键词后，从上往下浏览，如图：
![image](https://github.com/XIU2/UserScript/assets/53245925/57351976-fc17-4af0-9620-4031c5c027db)
若在向下拉的过程中没有找到想要的信息，就需要将页面拉到最顶部，并重新输入想要查找到关键词进行搜索
需求：
若可以将
body > div.logged-in.env-production.page-responsive > div.position-relative.js-header-wrapper > header > div (搜索框部分)
固定在浏览器访问的顶部，则可以在上厕所回到电脑前的时候，清晰想起自己找的是什么
或者添加一键返回页面顶端的按键，怎么说呢，就是使用更方便了吧

### 预期目标

在 `功能需求` 中

**Comment by XIU2** [comment]
这个脚本如名字所说，主要是负责加速下载的单一功能脚本，并不考虑将其功能扩充。
因此也不会添加和 加速下载 无关的功能。

****

但对于你这个需求我也可以提供一些帮助。

### 需求一：

如果你安装了 Stylus 扩展（用于向各个网站插入自定义的 CSS 样式，可以算是 CSS 版的油猴脚本[油猴脚本是向网站插入执行自定义的 JS 脚本]），那么可以添加一个样式规则，CSS 样式内容如下：
```css
/* 搜索栏浮动固定在网页顶部 */
header.AppHeader {
    position: fixed !important;
    width: 100% !important;
    top: 0px !important;
    z-index: 100 !important;
}
/* 网页向下移动一些距离，避免网页顶部内容被搜索栏遮挡 */
.application-main {
    margin-top: 64px !important;
}
```
样式规则匹配页面选择 `前缀`，然后写入下面这个即可。
```
https://github.com/search
```

当然，你可以选择新建一个油猴脚本，然后匹配这个 URL 前缀，并手动向网页中插入上述 CSS 样式。

****

### 需求二：

可以安装我的另一个 `[自动无缝翻页]` 油猴脚本，其支持 Github 搜索页（及其他页面）自动翻页，同时还附带了一个左下角的页码按钮，鼠标右键这个按钮就能回到网页顶部。

****

### 需求一 + 需求二：

我的 `[自动无缝翻页]` 油猴脚本支持自定义规则，包括自定义/补充内置规则，而规则中也支持给网页插入样式，因此只需要天玑一个自定义翻页规则，来给脚本内置的 `Github - Search` 规则添加一个  `style` 规则即可，这样脚本会自动在搜索页插入自定义的 CSS 样式来让搜索栏浮动固定在网页顶部，同时也可以使用脚本左下角的页码按钮来快速回到顶部。

复制粘贴到脚本 `自定义翻页规则` 默认的 `{ }` 中间保存（浏览器右上角 Tampermonkey 扩展图标内的脚本菜单）

```json
	"Github - Search": {
		"style": "header.AppHeader {position: fixed !important;width: 100% !important;top: 0px !important;z-index: 100 !important;} .application-main {margin-top: 64px !important;}",
		"inherits": true
	}
```
